name: core_aladim_package
description: api, ui, theme
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  http: 1.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - images/checked.gif
    - images/error.gif
    - images/checked2.gif